export const sourceRows = {
  sourceIdentifier: 'fake-project.supabase.co',
  siteOrigins: ['https://www.example.test'],
  targetMigrations: [
    { filename: '0001_content_tables.sql', sha256: 'a'.repeat(64) },
    { filename: '0003_project_operations.sql', sha256: 'b'.repeat(64) },
  ],
  projects: [{
    id: 'project-1',
    slug: 'aegean-home',
    title: 'Aegean Home',
    address: 'Coast Road',
    card_address: 'By the sea',
    price: 'EUR 500,000',
    short_description: 'Short',
    full_description: 'Full',
    intro_title: 'Welcome',
    categories: ['coastal'],
    status: 'published',
    sort_order: 2,
    cover_url: '/img/cover.webp',
    cover_focal_x: 41.5,
    cover_focal_y: 62.5,
    image_variants: {
      version: 1,
      images: {
        '/img/cover.webp': {
          width: 1600,
          height: 900,
          avif: [{ src: 'https://fake-project.supabase.co/storage/v1/object/public/project-media/project-1/cover.avif', width: 800, height: 450 }],
          webp: [{ src: '/media/project-1/cover.webp', width: 1200 }],
        },
      },
    },
    hero_type: 'video',
    hero_variant: 'immersive',
    hero_sound_enabled: true,
    hero_idle_ui: true,
    hero_url: 'https://fake-project.supabase.co/storage/v1/object/public/project-media/project-1/hero.mp4',
    hero_mobile_url: 'https://cdn.example.test/hero-mobile.mp4',
    hero_poster_url: '/img/hero-poster.webp',
    hero_videos: [{
      id: 'hero-1',
      desktopUrl: 'https://fake-project.supabase.co/storage/v1/object/public/project-media/project-1/playlist.mp4',
      mobileUrl: '/media/project-1/playlist-mobile.mp4',
      posterUrl: '/img/playlist-poster.webp',
    }],
    walkthrough_video_enabled: true,
    walkthrough_video_title: 'Tour',
    walkthrough_video_desktop_url: '/img/tour.mp4',
    walkthrough_video_mobile_url: null,
    walkthrough_video_poster_url: '/img/tour.webp',
    walkthrough_videos: [{
      id: 'walkthrough-1',
      desktopUrl: '/img/walkthrough.mp4',
      mobileUrl: 'https://www.example.test/media/project-1/walkthrough-mobile.mp4',
      posterUrl: null,
    }],
    hero_focal_x: 49,
    hero_focal_y: 51,
    intro_image_url: '/img/intro.webp',
    brochure_url: 'https://fake-project.supabase.co/storage/v1/object/public/project-documents/project-1/brochure.pdf',
    map_query: '40.1,23.2',
    map_url: 'https://maps.example.test/project-1',
    characteristics: [{ id: 'area', label: 'Area', value: '120m2', icon: 'area' }],
    benefits: [{ id: 'beach', title: 'Near beach', icon: 'https://fake-project.supabase.co/storage/v1/object/public/project-media/icons/beach.svg' }],
    floor_plan_groups: [{ id: 'floor-1', title: 'First floor', plans: [{ id: 'plan-1', title: 'Plan', imageUrl: '/img/plan.webp', alt: 'Plan' }] }],
    nearby_places: ['Beach'],
    translations: { el: { title: 'Κατοικία Αιγαίου', benefits: { beach: { title: 'Κοντά στη θάλασσα' } }, imageAlts: { 'image-1': 'Θέα' } } },
    seo_title: 'Aegean Home',
    seo_description: 'A home by the sea',
    published_at: '2026-07-01T10:00:00.000Z',
    created_at: '2026-06-01T10:00:00.000Z',
    updated_at: '2026-08-01T10:00:00.000Z',
    remaining_units: 0,
  }],
  projectImages: [{
    id: 'image-1',
    project_id: 'project-1',
    url: 'https://fake-project.supabase.co/storage/v1/object/public/project-media/project-1/gallery.webp',
    storage_path: 'project-1/gallery.webp',
    alt: 'Sea view',
    role: 'gallery',
    sort_order: 3,
    width: 2048,
    height: 1365,
    focal_x: 44,
    focal_y: 55,
    created_at: '2026-06-02T10:00:00.000Z',
  }],
  homepageVideos: [{
    id: 'home-video-1',
    title: 'Introduction',
    project_id: 'project-1',
    desktop_url: 'https://fake-project.supabase.co/storage/v1/object/public/site-media/home/desktop.mp4',
    desktop_storage_path: 'home/desktop.mp4',
    mobile_url: '/img/home-mobile.mp4',
    mobile_storage_path: null,
    sort_order: 1,
    is_active: true,
    created_at: '2026-06-03T10:00:00.000Z',
    updated_at: '2026-08-03T10:00:00.000Z',
  }],
  siteSettings: {
    id: 1,
    footer_terms_visible: true,
    footer_terms_pdf_url: 'https://fake-project.supabase.co/storage/v1/object/public/project-documents/legal/terms.pdf',
    footer_privacy_visible: true,
    footer_privacy_pdf_url: 'https://legal.example.test/privacy.pdf',
    footer_cookie_visible: true,
    footer_cookie_pdf_url: 'https://www.example.test/media/legal/cookies.pdf',
  },
};

export function reverseObjectKeys(value) {
  if (Array.isArray(value)) return value.map(reverseObjectKeys);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value).reverse().map(([key, item]) => [key, reverseObjectKeys(item)]));
}
